---
- name: Ensure os is up to date
  apt:
    update_cache: yes
    cache_valid_time: 300
    upgrade: full
    force_apt_get: yes

- name: Install packages
  apt:
    name: "{{ list_of_packages }}"
    state: present
    force_apt_get: yes
  tags: packages

- name: create /mnt points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{mount_points}}"

- name: mount disks
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount
    state: present
  loop: "{{hard_drives}}"

- name: mount mergerfs array
  mount:
    name: /mnt/storage
    src: /mnt/disk*
    opts: direct_io,defaults,allow_other,minfreespace=50G,fsname=mergerfs
    fstype: fuse.mergerfs
    # change to 'mounted' to auto mount
    state: present
