---
- hosts: debian-9-5

  gather_facts: yes
  become: yes

  roles:
    - docker
    - docker-compose
    - mergerfs
    - base-os
    - snapraid
    - login-banner
    - docker-apps-install
    # - snapraidrun
    # - fileshare