- include: mergerfs.yml
  tags: mergerfs

# - name: Install mergerfs package
#   apt:
#      deb: https://github.com/trapexit/mergerfs/releases/download/2.20.0/mergerfs_2.20.0.ubuntu-xenial_amd64.deb
#      state: present
# - name: build mergerfs from source in a container
#   include: build-src.yml
#   when: pkg_check.rc == 1

# an example of how to mount an array of disks using mergerfs
# don't forget to install fuse
# - name: mount mergerfs array
#   mount:
#     name: /mnt/storage
#     src: /mnt/disk*
#     opts: defaults,allow_other,minfreespace=50G,fsname=mergerfs
#     fstype: fuse.mergerfs
#     # change to 'mounted' to auto mount
#     state: present

# - name: mount mergerfs array
#   mount:
#     name: /mnt/storage
#     src: /mnt/disk*
#     opts: direct_io,defaults,allow_other,minfreespace=50M,fsname=mergerfs
#     fstype: fuse.mergerfs
#     # change to 'mounted' to auto mount
#     state: mounted
