---
- name: check if MergerFS is installed (changed=not)
  command: dpkg-query -W mergerfs
  register: pkg_check
  failed_when: pkg_check.rc > 1
  changed_when: pkg_check.rc == 1

# - name: Install mergerfs from maintainers site
#   get_url:
#     url: https://github.com/trapexit/mergerfs/releases/download/2.20.0/mergerfs_2.20.0.ubuntu-xenial_amd64.deb
#     dest: /tmp
#   when: pkg_check.rc == 1
- name: build mergerfs from source in a container
  include: build-src.yml
  when: pkg_check.rc == 1
