---
- name: install packages required by docker
  apt: pkg={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg2


- name: add docker repository key
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present
  register: add_repository_key
  ignore_errors: true

- name: add docker repository and update apt cache
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: install (or update) docker package
  apt:
    name: "docker-ce"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
  notify:
    - systemd daemon-reload
    - restart docker service

- name: start docker
  service:
    name: docker
    state: started
